import type { CompositionPlan, PageSchemaType } from "../page-schema/types/contracts.js";

const componentRenderers: Record<string, (title: string, dataKey?: string) => string> = {
  MetricCard: (title, dataKey) => `<MetricCard label="${title}" value={"--"} hint="${dataKey ?? "metric.value"}" />`,
  Tabs: (title) => `<Tabs tabs={["Overview", "Details", "History"]} defaultTab="Overview" aria-label="${title}" />`,
  ActivityFeed: (_title, dataKey) => `<ActivityFeed items={[]} dataKey="${dataKey ?? "events.recent"}" />`,
  Table: () => `<Table columns={[]} rows={[]} />`,
  Select: (title) => `<Select name="${title.toLowerCase().replace(/\s+/g, "-")}" label="${title}" options={[]} />`,
  Input: (title) => `<Input name="${title.toLowerCase().replace(/\s+/g, "-")}" label="${title}" />`,
  Badge: (title) => `<Badge label="${title}" variant="info" />`,
  Button: (title) => `<Button label="${title}" variant="secondary" />`,
  Card: (title) => `<Card><p>{"${title}"}</p></Card>`,
  SectionHeader: (title) => `<SectionHeader title="${title}" />`,
};

function sectionBlock(schema: PageSchemaType, plan: CompositionPlan, sectionId: string): string {
  const section = schema.sections.find((entry) => entry.id === sectionId);
  const mappedSection = plan.sections.find((entry) => entry.sectionId === sectionId);

  if (!section || !mappedSection) {
    return "";
  }

  const title = section.title ?? section.id;
  const lines: string[] = [];
  lines.push(`<section className=\"space-y-4\" aria-labelledby=\"${section.id}-title\">`);
  lines.push(`  <h2 id=\"${section.id}-title\" className=\"text-lg font-semibold\">${title}</h2>`);
  lines.push("  <Card>");
  lines.push("    <div className=\"space-y-3\">");

  for (const mapping of mappedSection.componentMappings) {
    const renderer = componentRenderers[mapping.concreteComponent] ?? componentRenderers.Card;
    lines.push(`      ${renderer(mapping.propsShape?.label ? String(mapping.propsShape.label) : title, section.dataKey)}`);
  }

  lines.push("    </div>");
  lines.push("  </Card>");
  lines.push("</section>");

  return lines.join("\n");
}

function unique<T>(values: T[]): T[] {
  return [...new Set(values)];
}

export function composeFrontend(pageSchema: PageSchemaType, compositionPlan: CompositionPlan): string {
  const usedComponents = unique(
    [
      ...compositionPlan.sections.flatMap((section) => section.componentMappings.map((mapping) => mapping.concreteComponent)),
      "Button",
      "Card",
      "EmptyState",
      "ErrorState",
      "LoadingState",
      "SectionHeader",
    ].sort()
  );

  const imports = `import { ${usedComponents.join(", ")} } from "@/components/registry";`;

  const actionButtons = pageSchema.actions
    .map((action) => `<Button label="${action.label}" variant="${action.variant ?? "secondary"}" />`)
    .join("\n          ");

  const sections = pageSchema.sections.map((section) => sectionBlock(pageSchema, compositionPlan, section.id)).join("\n\n      ");

  return `${imports}

export type PageState = "ready" | "loading" | "empty" | "error";

export default function ${toPascalCase(pageSchema.pageId)}Page() {
  const state: PageState = "ready";

  if (state === "loading") {
    return <LoadingState label="Loading ${pageSchema.pageType} data" />;
  }

  if (state === "empty") {
    return <EmptyState title="No data yet" description="There is no data available for this page." />;
  }

  if (state === "error") {
    return <ErrorState title="Unable to load page" message="Try again in a few moments." />;
  }

  return (
    <main className="mx-auto w-full max-w-7xl space-y-6 p-6">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <SectionHeader title="${humanize(pageSchema.pageId)}" description="Generated by Jarvis pipeline." />
        <div className="flex flex-wrap gap-2">
          ${actionButtons}
        </div>
      </header>

      ${sections}
    </main>
  );
}
`;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function humanize(value: string): string {
  const cleaned = value.replace(/[-_]+/g, " ").trim();
  if (!cleaned) {
    return "Generated Page";
  }

  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}
